package com.example.pogun.support;

import org.springframework.test.context.TestPropertySource;

@TestPropertySource(properties = {
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.url=jdbc:h2:mem:pogun_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.data.redis.host=localhost",
        "spring.data.redis.port=6379",
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect",
        "spring.jpa.show-sql=false",
        "PORT=0",
        "app.storage.s3.bucket=test-bucket",
        "app.storage.s3.region=ap-northeast-2",
        "app.startup-warmup.enabled=false",
        "APP_STARTUP_WARMUP_ENABLED=false",
        "app.schema-sync.enabled=false",
        "APP_SCHEMA_SYNC_ENABLED=false",
        "app.presence.store=memory",
        "app.presence.reconcile-interval-ms=1500",
        "APP_PRESENCE_RECONCILE_INTERVAL_MS=1500",
        "app.firebase.auth.mode=EMULATOR",
        "APP_FIREBASE_AUTH_MODE=EMULATOR",
        "app.firebase.auth.allow-emulator=true",
        "APP_FIREBASE_AUTH_ALLOW_EMULATOR=true",
        "app.firebase.auth.project-id=pogun-test",
        "FIREBASE_PROJECT_ID=pogun-test",
        "app.firebase.auth.emulator-project-id=pogun-test",
        "APP_FIREBASE_AUTH_EMULATOR_PROJECT_ID=pogun-test",
        "app.firebase.auth.web-api-key=test-key",
        "FIREBASE_WEB_API_KEY=test-key",
        "KAKAO_LOCAL_BASE_URL=https://dapi.kakao.com",
        "app.admin.console.session-ttl-seconds=28800",
        "APP_ADMIN_SESSION_TTL_SECONDS=28800",
        "app.admin.console.bootstrap-session-ttl-seconds=900",
        "APP_ADMIN_BOOTSTRAP_SESSION_TTL_SECONDS=900",
        "app.admin.console.challenge-ttl-seconds=300",
        "APP_ADMIN_CHALLENGE_TTL_SECONDS=300",
        "app.admin.console.webauthn.rp-id=test.local",
        "APP_ADMIN_WEBAUTHN_RP_ID=test.local",
        "app.admin.console.webauthn.rp-name=Pogun Admin Test",
        "APP_ADMIN_WEBAUTHN_RP_NAME=Pogun Admin Test",
        "app.admin.console.webauthn.allowed-origins=http://localhost",
        "APP_ADMIN_WEBAUTHN_ALLOWED_ORIGINS=http://localhost",
        "app.admin.console.webauthn.origin-rp-map=http://localhost=test.local",
        "APP_ADMIN_WEBAUTHN_ORIGIN_RP_MAP=http://localhost=test.local",
        "app.admin.console.email-verification.continue-url-map=http://localhost=http://localhost/login?adminVerify=done",
        "APP_ADMIN_VERIFY_CONTINUE_URL_MAP=http://localhost=http://localhost/login?adminVerify=done",
        "app.admin.console.email-verification.default-continue-url=http://localhost/login?adminVerify=done",
        "APP_ADMIN_VERIFY_DEFAULT_CONTINUE_URL=http://localhost/login?adminVerify=done",
        "app.notification.inactive-token-retention-days=30",
        "APP_NOTIFICATION_INACTIVE_TOKEN_RETENTION_DAYS=30",
        "app.notification.inactive-token-cleanup-cron=0 10 4 * * *",
        "APP_NOTIFICATION_INACTIVE_TOKEN_CLEANUP_CRON=0 10 4 * * *",
        "FIREBASE_KEY_BASE64=",
        "FIREBASE_CONFIG_JSON="
})
public abstract class IntegrationTestProperties {
}
